---
- hosts: all
  gather_facts: no
  tasks:
    - name: Get users with raw module
      raw: cat /etc/passwd
      register: passwd_content
      
    - name: Print users
      debug:
        var: passwd_content.stdout_lines